# Generated by Django 5.2.6 on 2025-11-22 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key: Universally unique identifier for this object.', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this object was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object is active.')),
                ('name', models.CharField(db_index=True, help_text="Account name (e.g., 'Checking', 'Savings', 'Visa Card').", max_length=255)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('INVESTMENT', 'Investment'), ('LOAN', 'Loan'), ('OTHER', 'Other')], db_index=True, default='BANK', help_text='Type of account.', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current account balance.', max_digits=18)),
                ('real_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current actual balance.', max_digits=18)),
                ('currency', models.CharField(default='CAD', help_text='Currency code (e.g., USD, CAD).', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the account.', null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key: Universally unique identifier for this object.', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this object was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object is active.')),
                ('name', models.CharField(db_index=True, help_text='Name of the category (e.g., Food, Salary, Utilities).', max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, help_text='Type of category: Income or Expense.', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description for the category.', null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Primary key: Universally unique identifier for this object.', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this object was last updated.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object is active.')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], db_index=True, help_text='Type of transaction.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=18)),
                ('currency', models.CharField(default='CAD', help_text='Currency code (e.g., USD, CAD).', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Optional note or notes about the transaction.', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the transaction.', null=True)),
                ('date', models.DateField(db_index=True, help_text='Date of the transaction.')),
                ('account', models.ForeignKey(help_text='Account associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='asset.account')),
                ('category', models.ForeignKey(blank=True, help_text='Category of the transaction. Only required for Income or Expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_category', to='asset.category')),
                ('to_account', models.ForeignKey(blank=True, help_text='Destination account for transfer transactions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='asset.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
